Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PKT.DataAccess;
using PKT.Models;
using System.Diagnostics;
using System.Collections.Generic;
using System.Data;

namespace PKT.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly DBContext _DBContext;
            
        public HomeController(ILogger<HomeController> logger, DBContext DBContext)
        {
            _DBContext = DBContext;
            _logger = logger;
        }

        public IActionResult Index()
        {
            UserInfo.UserDetails _UserDetails = new UserInfo.UserDetails();
            SessionHandler.ValidateSession(HttpContext, ref _UserDetails);
            ViewBag.UserName = _UserDetails.userName;
            ViewBag.CostName = _UserDetails.CostName;
            ViewBag.DOJ = _UserDetails.DOJ;
            ViewBag.PrivilegeName = _UserDetails.PrivilegeName;
            ViewBag.Privilege = Convert.ToInt32(_UserDetails.privilege);
            return View();
        }

        public IActionResult Agent()
        {
            UserInfo.UserDetails _UserDetails = new UserInfo.UserDetails();
            SessionHandler.ValidateSession(HttpContext, ref _UserDetails);
            ViewBag.UserName = _UserDetails.userName;
            ViewBag.CostName = _UserDetails.CostName;
            ViewBag.DOJ = _UserDetails.DOJ;
            ViewBag.PrivilegeName = _UserDetails.PrivilegeName;
            ViewBag.Privilege = Convert.ToInt32(_UserDetails.privilege);
            return View();

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        


    }
}

Controllers/QuestionerController.cs
using Microsoft.AspNetCore.Mvc;
using PKT.DataAccess;
using PKT.Models;
using System.Data;

using Microsoft.AspNetCore.Http;
using System.Text.Json;
using Newtonsoft.Json;

namespace PKT.Controllers
{
    public class QuestionerController : Controller
    {

        private readonly ILogger<QuestionerController> _logger;
        private readonly DBContext _DBContext;

        public QuestionerController(ILogger<QuestionerController> logger, DBContext DBContext)
        {
            _DBContext = DBContext;
            _logger = logger;
        }

        public IActionResult Index()
        {
            UserInfo.UserDetails _UserDetails = new UserInfo.UserDetails();
            SessionHandler.ValidateSession(HttpContext, ref _UserDetails);
            ViewBag.UserName = _UserDetails.userName; 
            ViewBag.Privilege = Convert.ToInt32(_UserDetails.privilege);
            return View();
        }


        [HttpPost]
        public IActionResult Get_Questions(string TestName, string ForType)
        {


           DataSet dt = _DBContext.Get_UI_Elements("PKT_Get_Questions", TestName, "", "", "", "", "", "");


            if (dt.Tables.Count > 0 && dt.Tables[0].Rows.Count > 0)
            {
                string Duration =  dt.Tables[0].Rows[0]["Duration"].ToString();

                List<Dictionary<string, object>> questions = new List<Dictionary<string, object>>();
                            
                foreach (DataRow row in dt.Tables[0].Rows)
                {
                    Dictionary<string, object> question = new Dictionary<string, object>
                    {
                        { "id", Convert.ToInt32(row["QuestionId"]) },
                        { "question", row["Question"].ToString() },
                        { "options", new List<Dictionary<string, object>>() },
                        { "correctAnswerId", -1 } ,
                        { "Marks",  Convert.ToInt32(row["Marks"]) },
                    };

                    foreach (DataColumn column in dt.Tables[0].Columns)
                    {
                        if (column.ColumnName.StartsWith("Id") && row[column] != DBNull.Value)
                        {
                            int id = Convert.ToInt32(row[column]);
                            string correspondingTextColumn = "Text" + column.ColumnName.Substring(2);
                            string text = row[correspondingTextColumn]?.ToString();


                            if (ForType == "QuestionEdits")
                            {
                                Dictionary<string, object> option = new Dictionary<string, object>
                                {
                                    { "id", id },
                                    { "text", text }
                                };

                                ((List<Dictionary<string, object>>)question["options"]).Add(option);

                                if ((int)question["correctAnswerId"] == -1)
                                {
                                    question["correctAnswerId"] = id;
                                }
                            }
                            else
                            {

                            if (!string.IsNullOrEmpty(text) && !text.Contains("\r"))
                            {
                                Dictionary<string, object> option = new Dictionary<string, object>
                                {
                                    { "id", id },
                                    { "text", text }
                                };

                                ((List<Dictionary<string, object>>)question["options"]).Add(option);

                                if ((int)question["correctAnswerId"] == -1)
                                {
                                    question["correctAnswerId"] = id;
                                }
                            }

                            }
                            
                        }
                    }

                    questions.Add(question);
                }

                string json = JsonConvert.SerializeObject(new { questions });

                return Json(new { status = "success", questions = json, Duration= Duration });
            }
            else
            {
                return Json(new { status = "failure" });
            }


        }

        [HttpPost]
        public IActionResult UpdateQuestions(string QuestionId, string Question, string Option1, string Option1Id,
                                             string Option2, string Option2Id, string Option3, string Option3Id, 
                                             string Option4, string Option4Id, string Option5, string Option5Id, string Status, string Marks)
        {

            string status = string.Empty, msg = string.Empty;
            UserInfo.UserDetails _UserDetails = new UserInfo.UserDetails();
            SessionHandler.ValidateSession(HttpContext, ref _UserDetails);

            DataSet dt = _DBContext.Update_Questions(QuestionId, Question, Option1, Option1Id, Option2, Option2Id, Option3, Option3Id, 
                                                        Option4, Option4Id, Option5, Option5Id, Status, Marks, _UserDetails.userId);

            if (dt.Tables[0].Rows.Count > 0)
            {
                if (dt.Tables[0].Rows[0]["MSG"].ToString().ToUpper().Equals("UPDATED"))
                {

                    status = "success";
                    msg = "Updated Successfully";

                }
            }
            else
            {
                status = "error";
                msg = "Not Updated";
               
            }

            return Json(new { status = status, msg = msg });

        }



        [HttpPost]
        public IActionResult Add_Questions_Entry(string[] selectedIds, string PKTId, string TimeTaken)
        {
            UserInfo.UserDetails _UserDetails = new UserInfo.UserDetails();
            SessionHandler.ValidateSession(HttpContext, ref _UserDetails);
            string status = string.Empty, msg = string.Empty;

            var idsString = string.Join(",", selectedIds) + ",";
            DataSet dt = _DBContext.Add_Questions_Entry(idsString, PKTId, TimeTaken, _UserDetails.userId);

            if (dt.Tables[0].Rows.Count > 0)
            {
                if (dt.Tables[0].Rows[0]["MSG"].ToString().ToUpper().Equals("ADDED"))
                {
                    status = "success";
                    msg = "Added Successfully";
                }
            }
            else
            {
                status = "error";
                msg = "Not Updated";

            }

            return Json(new { status = status, msg = msg });
        }




        [HttpPost]
        public IActionResult Get_Reports( string Criteria, string Id)
        {
            UserInfo.UserDetails _UserDetails = new UserInfo.UserDetails();
            SessionHandler.ValidateSession(HttpContext, ref _UserDetails);  

            DataSet dt = _DBContext.Get_UI_Elements(Criteria, _UserDetails.userId, Id, "", "", "", "", "");


            if (dt.Tables[0].Rows.Count > 0)
            {
                if (true)
                {

                    var Data = dt.Tables[0].AsEnumerable()
                    .Select(row => {
                        var questionObj = new Dictionary<string, object>();

                        foreach (DataColumn col in dt.Tables[0].Columns)
                        {
                            questionObj[col.ColumnName] = row.IsNull(col) ? "" : row[col];
                        }

                        return questionObj;
                    })
                    .ToList();

                    return Json(new { status = "success", Data });
                }
                else
                {
                    return Json(new { status = "error", msg = "No Records Found" });
                }
            }
            else
            {
                return Json(new { status = "error", msg = "No Records Found" });
            }


        }


    }
}

Controllers/UploadController.cs
using Microsoft.AspNetCore.Mvc;
using PKT.DataAccess;
using PKT.Models;
using System.Diagnostics;
using System;
using static PKT.Models.UserInfo;
using Newtonsoft.Json;
using System.Data.Common;
using System.Data;
//using static PKT.Models.UserInfo;

namespace PKT.Controllers
{
    public class UploadController : Controller
    {

        private readonly ILogger<QuestionerController> _logger;
        private readonly DBContext _DBContext; 

        public UploadController(ILogger<QuestionerController> logger, DBContext DBContext )
        {
            _DBContext = DBContext;
            _logger = logger; 

        }


        public IActionResult Index()
        {

            UserInfo.UserDetails _UserDetails = new UserInfo.UserDetails();
            SessionHandler.ValidateSession(HttpContext, ref _UserDetails);
            

            Upload _mod = new Upload();

            try
            {
                if (true)
                {
                    ViewBag.TempList = _DBContext.Get_UI_Elements("PKT_ProcessList", "", "", "", _UserDetails.userId, _UserDetails.privilege.ToString(), _UserDetails.region.ToString(), _UserDetails.userType);
                    ViewBag.UserName = _UserDetails.userName;
                    ViewBag.Privilege = Convert.ToInt32(_UserDetails.privilege);

                    return View();
                }
                else
                {
                    return RedirectToAction("SignIn", "Login");
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message.ToString());
            }

            
        }



 

        public IActionResult get_dropdown_list(string Criteria, string ID, string Condition2="")
        {
            try
            {
                UserDetails _UserDetails = new UserDetails();
                SessionHandler.ValidateSession(HttpContext, ref _UserDetails);
                var data = _DBContext.Get_UI_Elements(Criteria, ID, Condition2, "", _UserDetails.userId, _UserDetails.privilege.ToString(), _UserDetails.region.ToString(), _UserDetails.userType);
                string json = JsonConvert.SerializeObject(data);
                return Content(json, "application/json");
            }
            catch (Exception ex)
            {
                var error = new { error = ex.Message };
                string errorJson = JsonConvert.SerializeObject(error);
                return Content(errorJson, "application/json");
            }
        }



        [HttpPost]
        [Route("Base_Uploads")]
        public async Task<IActionResult> Base_Uploads([FromForm] IFormFile postedFile , [FromForm] string CostCode, [FromForm] string PKTName)
        {
            UserDetails _UserDetails = new UserDetails();
            SessionHandler.ValidateSession(HttpContext, ref _UserDetails);

            try
            {
                string ReqFileName = "PKT_Question_Base.csv";
                string FolderName = "Question_Base_Uploads";

                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Input", FolderName);

                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                if (postedFile != null)
                {
                    string fileName = Path.GetFileName(postedFile.FileName);

                    if (!fileName.Equals(ReqFileName, StringComparison.OrdinalIgnoreCase))
                    {
                        return Json(new { status = "error", Msg= "Please choose a valid file / Check the File Name!" });
                       // return BadRequest("");
                    }

                    string dest = Path.Combine(path, ReqFileName);
                    using (var fileStream = new FileStream(dest, FileMode.Create))
                    {
                        await postedFile.CopyToAsync(fileStream);
                    }

                    DataSet dt = _DBContext.Base_Uploads(CostCode, PKTName, _UserDetails.userId );

                    if (dt.Tables[0].Rows.Count > 0)
                    {
                        if (dt.Tables[0].Rows[0]["MSG"].ToString().ToUpper() == "UPLOADED")
                        {
                            return Json(new { status = "success", Msg = "The File has been uploaded Successfully!" });
 
                        }
                        else if (dt.Tables[0].Rows[0]["MSG"].ToString().ToUpper() == "ZEROUPLOAD")
                        {
                            return Json(new { status = "error", Msg = "No Rows Uploaded, Please confirm the File / Contact Administrator!" });
 
                        }
                        else  
                        {
                            return Json(new { status = "error", Msg = dt.Tables[0].Rows[0]["MSG"].ToString() });

                        }
                    }
                    else
                    {
                        return Json(new { status = "error", Msg = "No data found" });
 
                    }
                }
                else
                {
                    return Json(new { status = "error", Msg = "Please select a file to upload" });
                 }
            }
            catch (FileNotFoundException ex)
            {
                _logger.LogError(ex, "File not found error");
                return NotFound($"Error: {ex.Message}");
            }
            catch (DbException ex)
            {
                _logger.LogError(ex, "Database error");
                return StatusCode(500, $"Error: {ex.Message}");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Unexpected error");
                return StatusCode(500, $"Error: {ex.Message}");
            }
        }



        [HttpPost]
        public IActionResult Get_Reports(string CostId, string TestName  )
        {
            DataSet dt = _DBContext.Get_UI_Elements("PKT_TestReport", CostId, "", "", "", "", "", "");

            if (dt.Tables[0].Rows.Count > 0)
            {
                if (true)
                {
                    var Data = dt.Tables[0].AsEnumerable()
                    .Select(row => {
                        var questionObj = new Dictionary<string, object>();

                        foreach (DataColumn col in dt.Tables[0].Columns)
                        {
                            questionObj[col.ColumnName] = row.IsNull(col) ? "" : row[col];
                        }

                        return questionObj;
                    })
                    .ToList();

                    return Json(new { status = "success", Data });
                }
                else
                {
                    return Json(new { status = "error", msg="No Data Found" });
                }
            }
            else
            {
                return Json(new { status = "error", msg = "No Data Found" });
            }
  

        }
    }
}

Views/Home/Agent.cshtml
@{
    ViewData["Title"] = "Agent Home Page";
}

<style>
    #TempTable1 td, #TempTable1 th {
        padding: 5px !important;
        font-size: 12.5px;
    }

/*     .ui.basic.label {
    
        border: none !important;
        border-top-color: currentcolor;
        border-right-color: currentcolor;
        border-bottom-color: currentcolor;
        border-left-color: currentcolor;
    } */

 </style>

<style>

    .ui.rating .active.icon {
        color: rgb(100, 53, 201);
    }
</style>
<div class="ui container">


    <div class="ui large modal" id="TestHistoryModal">
        <div class="header">Test History</div>
        <div class="scrolling content">

            <div id="DivTempTable2" style="overflow: auto; "></div>
            <br />
            <br />
        </div>
    </div>


  
    <div class="main-content">


        <div class="ui segment violet">
            <div class="ui items">
                <div class="item">
                    <a class="ui tiny image" style="/*! border: 1px solid #6435c9; */box-shadow: 3px 3px 10px 0px gray;padding: 9px;border-radius: 5px;">
                        <img src="http://10.1.10.5/eTicket/Images/Logo/imarque_logo.png">
                    </a>
                    <div class="content">
                        <a class="header">@ViewBag.UserName</a>
                        <div class="description">

                            <p>@ViewBag.PrivilegeName | @ViewBag.DOJ</p>
                            <p> @ViewBag.CostName</p>
                        </div>
                    </div>
                </div>

            </div>

        </div>

        <div class="ui segment ">
            <a class="ui violet ribbon label large"> Test Records</a>
            <br />
            <br />

            <div id="DivTempTable1" style="overflow: auto; "></div>
        </div>

        <br />
        <br />
        <br />
        <br />
        <br />
    </div>
</div>


<script>


    getTestsReports();
     

    function getTestsReports() {
 
        $.ajax({
            url: '@Url.Action("Get_Reports", "Questioner")',
            type: "POST",
            data: { Criteria: "PKT_UserOverall_TestRecords" },
            success: function (result) {

                if (result != null) {
                    if (result != undefined && result.status == "success") {

                        if (Object(result).length === 0) {
                             $.notify("No Records Found", "error");
                            $('.spinner').css('display', 'block').fadeOut();
                            return;
                        }


                        var Action = `
                                <div class="ui animated button" tabindex="0"  onclick="Validate_Test(this,'{{td}}')">
                                      <div class="hidden content">Start </div>
                                  <div class=" visible content">
                                            <i class="icon share square"></i>
                              </div>
                            </div>
                        `;

                        var History = `<button class="ui circular basic icon button" id="{{td}}" onclick="getTestsHistoryReports(this.id)">
                                                  <i class="history violet  icon"></i>
                                            </button>`;

                        var NoOfAttempts = ` <div class="ui rating" data-rating="{{td}}" data-max-rating="5"></div>`;

                        var TestStatus = {
                            'Completed': ` <div class="ui green basic label" > <i class="icon checkmark "> </i> {{td}}  </div> `,
                            'ReTest': `<div class="ui red basic label"> <i class="icon undo"> </i> {{td}}  </div>`,
                            'Pending': `<div class="ui violet basic label"> <i class="attention icon"> </i> {{td}}  </div>`,
                        };


                        DynamicTable.renderTable({
                            jsonData: result.data,
                            targetElementId: 'DivTempTable1',
                            tableClasses: ["ui", "selectable", "table", "striped", "striped"],
                            columnModifiers: [
                                ["1", Action],
                                ["2", History],
                                ["4", TestStatus],
                                ["5", NoOfAttempts],
                            ]
                        });

 
                        $('.rating').rating('enable');


                       

                       return;

                    } else {
                        $.notify(result.msg, "error");
                        $('.spinner').css('display', 'block').fadeOut();
                        return;
                    }
                } else if (result.status == "error") {
                    $('.spinner').css('display', 'block').fadeOut();
                    $.notify(result.mod.msg, "error");
                    return;
                } else {
                    $('.spinner').css('display', 'block').fadeOut();
                    $.notify("Something went wrong", "error");
                    return;
                }
            }, failure: function (result) {
                $('.spinner').css('display', 'block').fadeOut();

                $.notify(result.responseText, "error");
                return;
            },
            error: function (result) {
                $('.spinner').css('display', 'block').fadeOut();

                $.notify(result.responseText, "error");
                return;
            }
        });
    }
 


            function Validate_Test(element, Id) {

        var closestTR = $(element).closest('tr');

        var thirdColumnText = $(closestTR).find('td:eq(2)').text();

        var fourthColumnHTML = $(closestTR).find('td:eq(3)').text().trim();;

      

                if (fourthColumnHTML == 'Completed') {
 
                    $.notify("Hey! The Test is Completed Already!", "info");
                    return;
                }
 

            $.ajax({
                url: "@Url.Action("get_dropdown_list", "Upload")",
                type: 'GET',
                dataType: 'json',
                data: { Id: Id, Criteria: 'PKT_PKTName' },
                success: function (data) {
                
                    TestName =data.Table[0].NAME;

                if (TestName == thirdColumnText) {

                        var url = `@Url.Action("index", "Questioner")?PKTName=${TestName}`;

                        var newTab = window.open(url, '_blank');
                        newTab.focus();

                    }else{

                    $.notify("Please Complete Previous Tests!", "error");

                    }
 


                },
                error: function () {
                    $.notify("Error fetching data", "error");
                }
            });
        }



    function getTestsHistoryReports(Ids) {

        $.ajax({
            url: '@Url.Action("Get_Reports", "Questioner")',
            type: "POST",
            data: { Criteria: "PKT_UserTestRecords", Id: Ids  },
            success: function (result) {

                if (result != null) {
                    if (result != undefined && result.status == "success") {

                        if (Object(result).length === 0) {
                            $.notify("No Records Found", "error");
                            $('.spinner').css('display', 'block').fadeOut();
 
                            return;
                        }


                        var Edit = `<button class='ui icon label' title="Click to View Questions" onclick="Get_Question('{{td}}')" >  {{td}}</button>`;
                        var Stars = ` <div class="ui star rating" data-rating="{{td}}" data-max-rating="5"></div>`;

                        var ReTestStatus = {
                            'true': ` <div class="ui red basic label" > <i class="attention icon"> </i> Retest  </div> `,
                            'false': `<div class="ui green basic label"> <i class="icon checkmark"> </i> Success  </div>`,
                        };

                        DynamicTable.renderTable({
                            jsonData: result.data,
                            targetElementId: 'DivTempTable2',
                            tableClasses: ["ui", "selectable", "table", "striped"],
                            columnModifiers: [
                                ["1", Edit],
                                ["4", Stars],
                                ["5", ReTestStatus],
                            ]
                        });

                        $('.rating').rating('enable');
                        $('#TestHistoryModal').modal('show');

                        return;

                    } else {
                        $.notify(result.msg, "error");
                        $('.spinner').css('display', 'block').fadeOut();
                         return;
                    }
                } else if (result.status == "error") {
                    $('.spinner').css('display', 'block').fadeOut();
                    $.notify(result.mod.msg, "error");
                    return;
                } else {
                    $('.spinner').css('display', 'block').fadeOut();
                    $.notify("Something went wrong", "error");
                    return;
                }
            }, failure: function (result) {
                $('.spinner').css('display', 'block').fadeOut();

                $.notify(result.responseText, "error");
                return;
            },
            error: function (result) {
                $('.spinner').css('display', 'block').fadeOut();

                $.notify(result.responseText, "error");
                return;
            }
        });
    }

</script>